In [46]:
import pandas as pd
from ucimlrepo import fetch_ucirepo

In [47]:
# Fetch dataset from UCI repository (ID 144 = German Credit Data)
statlog_german_credit_data = fetch_ucirepo(id=144)

# Extract features and target
X = statlog_german_credit_data.data.features
y = statlog_german_credit_data.data.targets

# Combine into a single DataFrame for easier manipulation
df = pd.concat([X, y], axis=1)

df.head()

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,...,Attribute12,Attribute13,Attribute14,Attribute15,Attribute16,Attribute17,Attribute18,Attribute19,Attribute20,class
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2

In [48]:
# Extract descriptive column names from metadata
column_descriptions = statlog_german_credit_data.variables['description'].tolist()

# Create mapping dictionary for renaming
rename_mapping = {}
for i, desc in enumerate(column_descriptions):
    old_name = df.columns[i]
    # Extract a clean name from the description
    new_name = desc.split(':')[0].strip() if ':' in desc else desc.split()[0].strip()
    rename_mapping[old_name] = new_name

# Manual overrides for clearer naming
rename_mapping = {
    'Attribute1': 'Checking_Account_Status',
    'Attribute2': 'Duration',
    'Attribute3': 'Credit_History',
    'Attribute4': 'Purpose',
    'Attribute5': 'Credit_Amount',
    'Attribute6': 'Savings_Account',
    'Attribute7': 'Employment_Duration',
    'Attribute8': 'Installment_Rate',
    'Attribute9': 'Personal_Status_Sex',
    'Attribute10': 'Other_Debtors',
    'Attribute11': 'Residence_Duration',
    'Attribute12': 'Property',
    'Attribute13': 'Age',
    'Attribute14': 'Other_Installment_Plans',
    'Attribute15': 'Housing',
    'Attribute16': 'Existing_Credits',
    'Attribute17': 'Job',
    'Attribute18': 'Num_Dependents',
    'Attribute19': 'Telephone',
    'Attribute20': 'Foreign_Worker',
    'class': 'Target'
}

df = df.rename(columns=rename_mapping)

In [49]:
# TARGET VARIABLE TRANSFORMATION
# ==============================================================================
# Transform target: 1 (Good) -> 0, 2 (Bad) -> 1
# This makes "Bad Credit" the positive class (event) for classification
df['Target'] = df['Target'].map({1: 0, 2: 1})

In [50]:
df.head()

,Checking_Account_Status,Duration,Credit_History,Purpose,Credit_Amount,Savings_Account,Employment_Duration,Installment_Rate,Personal_Status_Sex,Other_Debtors,...,Property,Age,Other_Installment_Plans,Housing,Existing_Credits,Job,Num_Dependents,Telephone,Foreign_Worker,Target
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,0
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,1
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,0
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,0
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,1

we will use this data to train the models

In [51]:
df.to_csv("../data/german_credit_data.csv", index=False)

In [52]:
# CATEGORICAL VALUE MAPPING
# ==============================================================================

# Comprehensive mapping dictionary based on UCI documentation
value_mappings = {
    'Checking_Account_Status': {
        'A11': '<_0_DM',
        'A12': '0-200_DM',
        'A13': '>=_200_DM',
        'A14': 'No_checking_account'
    },
    'Credit_History': {
        'A30': 'No_credits_/__all_paid',
        'A31': 'All_credits_paid_at_bank',
        'A32': 'Existing_credits_paid',
        'A33': 'Delay_in_past',
        'A34': 'Critical_account'
    },
    'Purpose': {
        'A40': 'Car_(new)',
        'A41': 'Car_(used)',
        'A42': 'Furniture/Equipment',
        'A43': 'Radio/Television',
        'A44': 'Domestic_appliances',
        'A45': 'Repairs',
        'A46': 'Education',
        'A47': 'Vacation',
        'A48': 'Retraining',
        'A49': 'Business',
        'A410': 'Others'
    },
    'Savings_Account': {
        'A61': '<_100_DM',
        'A62': '100-500_DM',
        'A63': '500-1000_DM',
        'A64': '>=_1000_DM',
        'A65': 'Unknown/None'
    },
    'Employment_Duration': {
        'A71': 'Unemployed',
        'A72': '<_1_year',
        'A73': '1-4_years',
        'A74': '4-7_years',
        'A75': '>=_7_years'
    },
    'Personal_Status_Sex': {
        'A91': 'Male:_divorced/separated',
        'A92': 'Female:_divorced/separated/married',
        'A93': 'Male:_single',
        'A94': 'Male:_married/widowed',
        'A95': 'Female:_single'
    },
    'Other_Debtors': {
        'A101': 'NoNe',
        'A102': 'Co-applicant',
        'A103': 'Guarantor'
    },
    'Property': {
        'A121': 'Real_estate',
        'A122': 'Building_society_savings',
        'A123': 'Car_or_other',
        'A124': 'Unknown/None'
    },
    'Other_Installment_Plans': {
        'A141': 'Bank',
        'A142': 'Stores',
        'A143': 'NoNe'
    },
    'Housing': {
        'A151': 'Rent',
        'A152': 'Own',
        'A153': 'For_free'
    },
    'Job': {
        'A171': 'Unemployed/Unskilled',
        'A172': 'Unskilled_-_resident',
        'A173': 'Skilled_employee',
        'A174': 'Management/Self-employed'
    },
    'Telephone': {
        'A191': 'NoNe',
        'A192': 'Yes'
    },
    'Foreign_Worker': {
        'A201': 'Yes',
        'A202': 'No'
    }
}

# Apply mappings to categorical columns
for column, mapping in value_mappings.items():
    if column in df.columns:
        df[column] = df[column].map(mapping).fillna(df[column])

the data seens to be clean and no missing values

In [53]:
df.isnull().sum()

Checking_Account_Status    0
Duration                   0
Credit_History             0
Purpose                    0
Credit_Amount              0
Savings_Account            0
Employment_Duration        0
Installment_Rate           0
Personal_Status_Sex        0
Other_Debtors              0
Residence_Duration         0
Property                   0
Age                        0
Other_Installment_Plans    0
Housing                    0
Existing_Credits           0
Job                        0
Num_Dependents             0
Telephone                  0
Foreign_Worker             0
Target                     0
dtype: int64

we will use this data to EDA

In [54]:
df.to_csv("../data/german_credit_data_mapping.csv", index=False)